<?php

namespace App\Services\Accounting;

use App\Models\Accounting\Account;
use App\Models\Accounting\JournalEntry;
use App\Models\Accounting\JournalLine;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * The only writer to the books.
 *
 * Rules enforced here (so no controller, command or import can break them):
 *  - an entry has at least two lines, each a debit OR a credit (never both, never zero);
 *  - total debits equal total credits, compared in whole kobo (integers), not floats;
 *  - lines may only use active accounts;
 *  - nothing can be posted, voided or corrected in a closed period;
 *  - a posted entry is never edited or deleted. Mistakes are fixed by a reversing entry
 *    (void) and, for a correction, a fresh entry linked to it.
 */
class Ledger
{
    /**
     * Entries generated by the system. They can be voided only by the service that owns them (a receipt,
     * for instance, through Costing::voidReceipt) — never by hand from the transactions list.
     */
    public const SYSTEM_SOURCES = ['sales', 'cogs', 'receipt', 'adjustment', 'opening_stock'];

    private const PREFIX = [
        'income' => 'INC', 'expense' => 'EXP', 'transfer' => 'TRF',
        'journal' => 'JNL', 'sales' => 'SAL', 'opening' => 'OPN',
    ];

    /** "1234.5" / 1234.5 / "1,234.50" -> 123450 (kobo). Rounds half up, never truncates. */
    public static function toKobo($amount): int
    {
        return (int) round(((float) str_replace(',', '', (string) $amount)) * 100);
    }

    public static function fromKobo(int $kobo): float
    {
        return $kobo / 100;
    }

    /**
     * @param array $data {
     *   date: Y-m-d, type: income|expense|transfer|journal|sales|opening, description: string,
     *   party?: string, payment_reference?: string, source?: string, source_key?: string,
     *   created_by?: int, replaces_entry_id?: int, reverses_entry_id?: int,
     *   allow_locked?: bool,   // only for system corrections that pick a legal date themselves
     *   lines: [ { account_id|account_code, debit?, credit?, memo? } ]
     * }
     */
    public function post(array $data): JournalEntry
    {
        $date = Carbon::parse($data['date'])->toDateString();
        if (empty($data['allow_locked'])) {
            $this->assertOpen($date);
        }
        $lines = $this->normaliseLines($data['lines'] ?? []);
        $totalKobo = array_sum(array_column($lines, 'debit'));

        return DB::transaction(function () use ($data, $date, $lines, $totalKobo) {
            $entry = JournalEntry::create([
                'entry_date' => $date,
                'type' => $data['type'],
                'description' => mb_substr(trim($data['description']), 0, 255),
                'party' => isset($data['party']) ? mb_substr(trim($data['party']), 0, 150) : null,
                'payment_reference' => isset($data['payment_reference']) ? mb_substr(trim($data['payment_reference']), 0, 100) : null,
                'total' => self::fromKobo($totalKobo),
                'status' => 'posted',
                'source' => $data['source'] ?? null,
                'source_key' => $data['source_key'] ?? null,
                'reverses_entry_id' => $data['reverses_entry_id'] ?? null,
                'replaces_entry_id' => $data['replaces_entry_id'] ?? null,
                'created_by' => $data['created_by'] ?? null,
            ]);

            foreach ($lines as $line) {
                JournalLine::create([
                    'journal_entry_id' => $entry->id,
                    'account_id' => $line['account_id'],
                    'debit' => self::fromKobo($line['debit']),
                    'credit' => self::fromKobo($line['credit']),
                    'memo' => $line['memo'],
                ]);
            }

            // sequential, human-friendly reference derived from the id (EXP-000123)
            $entry->reference = (self::PREFIX[$data['type']] ?? 'JNL') . '-' . str_pad((string) $entry->id, 6, '0', STR_PAD_LEFT);
            $entry->save();

            return $entry->load('lines.account');
        });
    }

    /**
     * Cancel an entry by posting its mirror image. The original stays in the books, marked
     * VOID and pointing at the reversal, so the trail is complete and the net effect is zero.
     */
    public function void(JournalEntry $entry, string $reason, ?int $userId = null, bool $bySystem = false): JournalEntry
    {
        return DB::transaction(function () use ($entry, $reason, $userId, $bySystem) {
            $entry = JournalEntry::whereKey($entry->id)->lockForUpdate()->firstOrFail();

            if ($entry->status === 'void') {
                throw new LedgerException('This transaction has already been voided.');
            }
            if ($entry->isReversal()) {
                throw new LedgerException('A reversing entry cannot be voided. Post a new transaction instead.');
            }
            if (!$bySystem && in_array($entry->source, self::SYSTEM_SOURCES, true)) {
                throw new LedgerException(match ($entry->source) {
                    'sales', 'cogs' => 'Sales and cost-of-sales summaries are generated from orders and cannot be voided. Change the order, then re-sync sales.',
                    'receipt' => 'A stock delivery is corrected from Receive stock (void the delivery there), not from here.',
                    'adjustment' => 'A stock adjustment cannot be voided here. Record an opposite adjustment instead.',
                    default => 'This entry was created by the system and cannot be voided by hand.',
                });
            }
            $this->assertOpen($entry->entry_date->toDateString());

            $reversal = $this->post([
                'date' => $entry->entry_date->toDateString(),
                'type' => $entry->type,
                'description' => 'Reversal of ' . $entry->reference . ': ' . $reason,
                'party' => $entry->party,
                'source' => 'reversal',
                'source_key' => (string) $entry->id,
                'reverses_entry_id' => $entry->id,
                'created_by' => $userId,
                'lines' => $entry->lines->map(fn ($l) => [
                    'account_id' => $l->account_id,
                    // the mirror image
                    'debit' => (float) $l->credit,
                    'credit' => (float) $l->debit,
                    'memo' => $l->memo,
                ])->all(),
            ]);

            $entry->status = 'void';
            $entry->voided_at = now();
            $entry->voided_by = $userId;
            $entry->void_reason = mb_substr($reason, 0, 255);
            $entry->reversed_by_entry_id = $reversal->id;
            $entry->save();

            return $reversal;
        });
    }

    /** Correct a transaction: void the old one and post the corrected version, linked both ways. */
    public function replace(JournalEntry $old, array $data, string $reason = 'Corrected'): JournalEntry
    {
        return DB::transaction(function () use ($old, $data, $reason) {
            $this->void($old, $reason, $data['created_by'] ?? null);
            $new = $this->post($data + ['replaces_entry_id' => $old->id]);
            JournalEntry::whereKey($old->id)->update(['replaced_by_entry_id' => $new->id]);

            return $new;
        });
    }

    public function assertOpen(string $date): void
    {
        $closed = AccountingSettings::closedThrough();
        if ($closed && Carbon::parse($date)->lte(Carbon::parse($closed))) {
            throw new LedgerException(
                'The books are closed through ' . Carbon::parse($closed)->format('j M Y') . '. '
                . 'Use a later date, or ask an administrator to reopen the period.'
            );
        }
    }

    /**
     * Validate the lines and reduce them to integer kobo. Throws a LedgerException with a
     * message a bookkeeper can act on.
     *
     * @return array<int, array{account_id:int, debit:int, credit:int, memo:?string}>
     */
    private function normaliseLines(array $lines): array
    {
        if (count($lines) < 2) {
            throw new LedgerException('A transaction needs at least two lines (something is debited and something is credited).');
        }

        $codes = array_filter(array_column($lines, 'account_code'));
        $codeToId = $codes ? Account::whereIn('code', $codes)->pluck('id', 'code')->all() : [];
        $ids = [];
        foreach ($lines as $line) {
            $ids[] = $line['account_id'] ?? ($codeToId[$line['account_code'] ?? ''] ?? null);
        }
        $accounts = Account::whereIn('id', array_filter($ids))->get()->keyBy('id');

        $out = [];
        $debits = 0;
        $credits = 0;
        foreach ($lines as $i => $line) {
            $accountId = $ids[$i];
            $account = $accounts[$accountId] ?? null;
            if (!$account) {
                throw new LedgerException('Line ' . ($i + 1) . ' uses an account that does not exist.');
            }
            if (!$account->is_active) {
                throw new LedgerException('The account "' . $account->name . '" is inactive. Reactivate it or choose another.');
            }

            $debit = self::toKobo($line['debit'] ?? 0);
            $credit = self::toKobo($line['credit'] ?? 0);
            if ($debit < 0 || $credit < 0) {
                throw new LedgerException('Amounts cannot be negative. Use the opposite side (debit/credit) instead.');
            }
            if (($debit > 0) === ($credit > 0)) {
                throw new LedgerException('Line ' . ($i + 1) . ' (' . $account->name . ') must have either a debit or a credit — not both, and not zero.');
            }

            $debits += $debit;
            $credits += $credit;
            $out[] = ['account_id' => $account->id, 'debit' => $debit, 'credit' => $credit, 'memo' => isset($line['memo']) ? mb_substr((string) $line['memo'], 0, 255) : null];
        }

        if ($debits !== $credits) {
            throw new LedgerException(
                'The transaction does not balance: debits are ' . number_format($debits / 100, 2)
                . ' but credits are ' . number_format($credits / 100, 2) . '.'
            );
        }

        return $out;
    }
}
